#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageJson = JSON.parse(
  readFileSync(join(__dirname, '..', 'package.json'), 'utf-8')
);

const versionFile = `// Auto-generated by scripts/generate-version.js
export const VERSION = '${packageJson.version}';
export const PACKAGE_NAME = '${packageJson.name}';
`;

writeFileSync(join(__dirname, '..', 'src', 'version.ts'), versionFile);
console.log(`Generated src/version.ts with version ${packageJson.version}`);
